[dev]
  autoLaunch = false

[functions]
  directory = "netlify/functions"

[build]
  publish = "dist/public"
  edge_functions = "netlify/edge-functions"

[functions.strangler]
  included_files = ["dist/public/404.html"]

[[edge_functions]]
  path = "/"
  function = "homepage-redirect"

[[edge_functions]]
  path = "/.netlify/functions/github-proxy"
  function = "github-proxy-auth"

[[edge_functions]]
  path = "/.netlify/functions/github-proxy/*"
  function = "github-proxy-auth"

[[headers]]
  for = "/set-drupal-session"
  [headers.values]
    Content-Security-Policy = "frame-ancestors *"
